# Generated by Django 5.0.4 on 2025-04-01 02:16

import traffic_offence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FineCollect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vRno', models.CharField(max_length=50, verbose_name='Vehicle Registration Number')),
                ('collected_fine', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Collected Fine Amount')),
                ('trafficviolation', models.TextField(verbose_name='Traffic Violation Details')),
                ('police_id', models.CharField(max_length=100, verbose_name='Police ID')),
                ('police_name', models.CharField(max_length=100, verbose_name='Police Officer Name')),
                ('collect_date', models.DateField(auto_now_add=True, verbose_name='Collection Date')),
                ('collect_time', models.TimeField(default=traffic_offence.models.current_time, verbose_name='Collection Time')),
            ],
            options={
                'verbose_name': 'Fine Collection',
                'verbose_name_plural': 'Fine Collections',
                'db_table': 'fine_collect',
            },
        ),
        migrations.CreateModel(
            name='FoundVehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=255)),
                ('vehicle_num', models.CharField(max_length=50, unique=True)),
                ('engine_num', models.CharField(max_length=100, unique=True)),
                ('vehicle_foundcity', models.CharField(max_length=100)),
                ('vehicle_foundstate', models.CharField(max_length=100)),
                ('vehicle_pic', models.ImageField(upload_to='vehicle_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='NoParking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=255)),
                ('vnum', models.CharField(max_length=50, unique=True)),
                ('vaddr', models.TextField()),
                ('vnear_by', models.CharField(max_length=255)),
                ('v_lift_typ', models.CharField(max_length=100)),
                ('Tiger_id', models.IntegerField()),
                ('collect_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'no_parking',
            },
        ),
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('fine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterTrafficOffence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_regno', models.CharField(max_length=20, unique=True)),
                ('violation_date', models.DateField()),
                ('violation_place', models.CharField(max_length=255)),
                ('violation_type', models.CharField(max_length=100)),
                ('violation_desc', models.TextField()),
                ('violation_pic', models.ImageField(blank=True, null=True, upload_to='violation_pics/')),
                ('vtype', models.CharField(max_length=50)),
                ('vowner_name', models.CharField(max_length=100)),
                ('vaadhar', models.CharField(max_length=12, unique=True)),
                ('vr_address', models.TextField()),
                ('vr_city', models.CharField(max_length=100)),
                ('vr_state', models.CharField(max_length=100)),
                ('engine_num', models.CharField(max_length=50, unique=True)),
                ('comp_vehicle', models.CharField(max_length=100)),
                ('com_type', models.CharField(blank=True, max_length=100, null=True)),
                ('fine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fine_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=50)),
                ('offence_cat', models.CharField(max_length=100)),
                ('offence_subcat', models.CharField(max_length=100)),
                ('fine_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('compid', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RTO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('aadhar_card_no', models.CharField(max_length=12, unique=True)),
                ('r_address', models.TextField()),
                ('r_city', models.CharField(max_length=100)),
                ('r_state', models.CharField(max_length=100)),
                ('vehicle_num', models.CharField(max_length=20, unique=True)),
                ('engine_num', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TigerVehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tigerPolName', models.CharField(max_length=255)),
                ('tigerStatName', models.CharField(max_length=255)),
                ('stat_address', models.TextField()),
                ('tigeruser', models.CharField(max_length=150, unique=True)),
                ('tigerpass', models.CharField(max_length=150)),
                ('contact_no', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tiger_vehicle',
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('guest', 'Guest')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15, unique=True)),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViolatorComplaint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_regno', models.CharField(max_length=20, unique=True)),
                ('violation_date', models.DateField()),
                ('violation_place', models.CharField(max_length=255)),
                ('violation_type', models.CharField(max_length=100)),
                ('violation_time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('pic_traffic_violator', models.ImageField(blank=True, null=True, upload_to='violator_images/')),
            ],
        ),
    ]
