# Generated by Django 5.0.4 on 2025-04-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_offence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noparking',
            name='Tiger_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='noparking',
            name='collect_date',
            field=models.DateField(auto_now_add=True, verbose_name='Collection Date'),
        ),
    ]
